lasp-lang/partisan

src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service_client.erl, src/partisan_peer_service_server.erl
Allow peers to conenct with a tag, and reserve slots for those peers in
the active view, to guarantee that we are always connected to certain
types of peers.
=> Store a list of reserved slots.

src/partisan.app.src, src/partisan_config.erl
These changes I think will allow lasp to not require partisan as an included application because you can set ip, port and peer service through the OS vars as is done in lasp itself currently.
I have a separate PR coming for lasp if this is merged.
=> support OS var configuration of ip, port and peer service

.gitignore, Makefile, src/partisan.app.src, src/partisan_config.erl, src/partisan_peer_connection.erl, src/partisan_peer_connection.hrl, src/partisan_peer_service_client.erl, src/partisan_peer_service_server.erl, test/partisan_SUITE.erl, test/partisan_SUITE_data/make_certs.erl
* Depend on `ssl` app to be started
* Add default options for TLS to `partisan_config`
* Wrap socket calls in `partisan_peer_connection` module so that we
can transparently use `gen_tcp` or `ssl` depending on configuration
* Add `partisan_peer_connection.hrl` with macros for matching tags on
`active` messages
* Allow `partisan_SUITE` to run tests in parallel by generating node
names
* Add test group to `partisan_SUITE` that runs a test over TLS
* Import `make_certs.erl` from OTP to generate certificates and keys
for the TLS-enabled tests. Add `RAND` file generation to the
`Makefile` for use by `make_certs`
=> Enable TLS for peer connections

Makefile
No need for `rebar3 as test ct`, the test profile is implicit when running common test as documented in https://www.rebar3.org/docs/profiles
=> Generate coverage report at the end of ct

src/partisan_peer_service_console.erl, src/partisan_peer_service_events.erl, src/partisan_peer_service_server.erl
Use a single one defined in partisan_peer_service.
=> Drop duplicate manager() methods

src/partisan_hyparview_peer_service_manager.erl
While joining a new node on the contact node, try
and connect to all nodes in the active view before
sending the FORWARD_JOIN message
=> Try connect to peer before sending FORWARD_JOIN

src/partisan_default_peer_service_manager.erl
Resolve an issue in the default connection manager where a new join request would not be connected immediately.
=> Ensure we force connection immediately.

src/partisan_hyparview_peer_service_manager.erl
Fix the case where, on join, a  member is dropped
from the active view and therefore should not be
considered when forwarding joins.
The initial active view was being used instead of
the one that resulted from a possible removal.
=> Only consider active view members on forward join

test/partisan_SUITE.erl
Instead of just waiting a predefined amount of time
and then check for connectedness and symmetry, set
a ceiling on that time and periodically check for completion.
=> Remove race condition while waiting for graph to build

include/partisan.hrl, src/partisan_config.erl, src/partisan_connection_cache.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service_client.erl, src/partisan_peer_service_server.erl, src/partisan_sup.erl, test/partisan_SUITE.erl
=> Connection multiplexing

src/partisan_hyparview_peer_service_manager.erl
When a peer disconnects us, don’t consider it as a candidate to
move back from the passive view into the active one.
=> Exclude disconnecting peer on neighbor request

include/partisan.hrl, src/partisan_client_server_peer_service_manager.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service_connections.erl, src/partisan_static_peer_service_manager.erl, src/partisan_util.erl, test/partisan_SUITE.erl
This is a continuation of the discussion in #54 and supersedes the changes in that PR.
Peer Manager connections are now abstracted in the `partisan_peer_service_connections` module, it currently only offers `new/0` and `find/2`. It this change looks ok, following PRs will contain the remaining methods of the abstraction.
Store a three tuple node_spec() in connections
dictionary as key instead of a node name atom.
Introduce new module that abstracts away the
peer service connections dictionary.
=> Refactor connections dictionary

src/partisan_connection_cache.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_sup.erl
684f01f2bfe86c9d4baf33a21b6d96c147fb532c fixes clobbering of the cache by other managers.
0faddba6ea078d63047eca07f25fdb82338a21ed gets the cache to actually be used as it was just trapping to `gen_server:call` all the time.
=> Fix connection cache

README.md, include/partisan.hrl, src/partisan_client_server_peer_service_manager.erl, src/partisan_config.erl, src/partisan_connection_cache.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service.erl, src/partisan_peer_service_client.erl, src/partisan_peer_service_connections.erl, src/partisan_peer_service_manager.erl, src/partisan_pool.erl, src/partisan_pool_sup.erl, src/partisan_socket.erl, src/partisan_static_peer_service_manager.erl, src/partisan_util.erl, test/partisan_SUITE.erl
=> Allow multiple bind addresses.

src/partisan.app.src
* Join API now expects a map containing listen addresses
=> Bump version to 1.0.0

src/partisan_config.erl
Without this the random `PeerPort` would always be used for `listen_addrs` of the node, which would break for any other node that uses Erlang rpc to look at another nodes listen port.
=> don't override peer port setting with random port in listen_addrs

include/partisan.hrl, src/partisan.app.src, src/partisan_config.erl, src/partisan_peer_service_manager.erl
Also removes unneeded (since `listen_addrs` will get set on startup) uses of `?LISTEN_ADDRS` that are confusing since they won't be used but that isn't obvious without investigating the code further.
=> remove use of IP and PEER_PORT os vars

src/partisan_config.erl, test/partisan_SUITE.erl
Resolve the node name and use the node name for the default IP address, instead of 127.0.0.1.
=> Use the resolution of node name.

src/partisan_client_server_peer_service_manager.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service.erl, src/partisan_peer_service_manager.erl, src/partisan_static_peer_service_manager.erl, test/partisan_SUITE.erl
Some applications will need to forward messages on to processes where the remote side is not necessarily a gen_server.
=> Provide cast/forward behavior.

src/partisan_peer_connection.erl
If a node has a monotonic channel to another node, only dispatch the last message from a process that could contain an overloaded mailbox.
Periodically, ensure that a message is sent to prevent the obvious race condition where messages are being delivered too fast, dropped, and no transmissions occur.
=> Add support for monotonic channels.

src/partisan_pool_sup.erl, src/partisan_socket.erl
One partisan_socket process is launched for every
listen address, this means there must be a different
id per supervisor spec and each process must not
register it's name.
=> Don't crash when using multiple addresses

Makefile, src/partisan_default_peer_service_manager.erl, test/partisan_SUITE.erl
When leaving, don't shutdown, but reset membership back to node only.  Ensure gossip always uses all peers, because a random fanout doesn't guarantee that a leaving node will observe itself leaving the cluster immediately.
=> Fix cluster leaves.

src/partisan_default_peer_service_manager.erl, test/partisan_SUITE.erl
If a node receives a message that it's supposed to be evicted from the cluster, it needs to reset it's state, shutdown and restart, thereby clearing all connections, before it can hear about old state on a existing open channel -- otherwise, that state will be merged back in and the node will never actually leave the cluster.
=> Handle leaves properly.

src/partisan_default_peer_service_manager.erl
Don't serialize on the backend when receiving a message: this causes an
additional message copy and induces serialization where not necessary.
=> Attempt to receive message without serializing.

src/partisan_client_server_peer_service_manager.erl
when writing data using `term_to_binary`, and loading from disk, I think using `binary_to_term` just decode the data out, not match the `{ok, State}` pattern.
=> fix result

src/partisan_peer_service_client.erl
instead of logging it as an error, display a warning when connecting the client
=> display connect error as warning

src/partisan_default_peer_service_manager.erl
Fix the sync_join command so that the call is actually synchronous.
=> Make sync_join synchronous.

src/partisan_causality_backend.erl, src/partisan_client_server_peer_service_manager.erl, src/partisan_config.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service_manager.erl, src/partisan_static_peer_service_manager.erl, src/partisan_util.erl, test/partisan_SUITE.erl
Partisan now does not allow process identifiers to be sent because they require distributed Erlang for rewriting the process identifiers to be local.  Instead, register a local name to the process identifier and send that, so that processes can transmit process identifiers without transmitting the identifiers themselves.
=> Convert pids to gensym to enable sending pids transparently.

src/partisan_client_server_peer_service_manager.erl, src/partisan_default_peer_service_manager.erl, src/partisan_static_peer_service_manager.erl
net_kernel:connect/1 is missing in erlang/otp 21, use the net_kernel:connect_node/1 instead.
And add net_kernel app to dialyzer anlysis.
=> use net kernel connect node

src/partisan_hyparview_peer_service_manager.erl, src/partisan_hyparview_xbot_peer_service_manager.erl, src/partisan_peer_service_connections.erl, test/partisan_SUITE.erl
I recheck the code for many times, and find that, the manager process dies and restarts, the connections are all lost, but the active and the passive are still remained. So the other network close, the active will not be deleted and not correct.The solution I think is only persist the epoch. 
The xbot module does have the same problem, I don’t know the solution is correct or not,  if the pr is merged, I will make a new pr to the xbot module.
Feedback is needed.
=> Change persist epoch

include/partisan.hrl, src/partisan_config.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_xbot_peer_service_manager.erl, src/partisan_peer_service_manager.erl
Nodes performing a synchronous join will wait to proceed until they have established all outbound connections.  They will periodically check and unblock the join when all connections have been open.  However, this check only happens when receiving incoming connections, and therefore a race exists where the last node may join before all outgoing connections are established and thereby prevent the join from ever finishing.  To resolve, periodically check the blocked joins on the connection interval and unblock joins if they happen to be fulfilled (by opening of outgoing connections) at the next check interval.
However, this uncovered a further problem.  When the X-BOT backend was created, only some of the node specifications were modified to add the new X-BOT parameters, not all, therefore …
=> Address X-BOT regression and race condition.

src/partisan_peer_connection.erl
Otherwise, < 16/64KB will result in a performance hit with parallel connections due to Nagle's algorithm.
=> Disable Nagle on sender.

rebar.config, rebar.lock, src/partisan_util.erl
Like OTP gen_servers this changes brings support of the via syntax
allowing partisan to find a process registered through an alternative
process registry.
=> handle {via, Module, Name} tuple when receiving a message

src/partisan.app.src
version number in the app.src is still the old one
=> fix version number

src/partisan_monitor.erl, src/partisan_sup.erl
Given a `{partisan_remote_reference, Node, {partisan_process_reference,
PidAsList}}`, you will be able to call `partisan_monitor:monitor/1` in order to
monitor the process. This will message a named process on the `Node` to begin
monitoring the `PidAsList` as a proxy for the calling process, returning a
`partisan_encoded_reference`.
If the monitored process dies, it will send the down message to the local
`partisan_monitor` process which will do a lookup and forward the message off to
the remote monitoring process.
You can also call `partisan_monitor:demonitor/1`, handing it the
`partisan_encoded_reference`, in order to stop monitoring the remote process.
This is in reference to #45
=> Basic version of remote monitoring

src/partisan_pluggable_peer_service_manager.erl
This change solves a function clause error. Function partisan_pluggable_peer_service_manager:internal_leave/2 must receive a map in the first argument.
=> Ensures that internal_leave/2 receives a map.

README.md
`<br>` doesn't seem to be supported by `ex_doc`:
Using a end-of-line double space convention instead fixes this:
=> fix ex_doc line break in readme
