lasp-lang/partisan

README.md, include/partisan.hrl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_sup.erl
This is a WIP integration branch for HyParView support for partisan.
=> Integrate HyParView

README.md, src/partisan_client_server_peer_service_manager.erl, test/partisan_SUITE.erl
=> Allow servers to connect to servers.

include/partisan.hrl, src/partisan_client_server_peer_service_manager.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service_manager.erl, test/partisan_SUITE.erl
=> Partition injector.

src/partisan_client_server_peer_service_manager.erl, src/partisan_default_peer_service_manager.erl
=> Do not gossip membership in client server

src/partisan_peer_service_server.erl
Not sure what to do if the data on the socket is not an error or normal close. Should we continue to receive until it is either empty or gives the error or normal close response?
@seancribbs @evanmcc ?
=> remove flush socket from server socket 'down' handling

src/partisan_peer_connection.erl, test/partisan_SUITE.erl
Add test coverage of message forwarding functionality
Fix ssl race condition on accept
This is a pre-requisite to the refactor discussed in #54
=> Add forward message test coverage

src/partisan_config.erl
=> Change default from client/server to the default manager.

src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service_client.erl, src/partisan_peer_service_server.erl, test/partisan_SUITE.erl
Add more logging while running tests that improves
understanding of the algorithm to newcomers.
=> Improve hyparview test logging

src/partisan_peer_service.erl
=> Add forward_message/3 to API

src/partisan_client_server_peer_service_manager.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service.erl, src/partisan_peer_service_manager.erl, src/partisan_static_peer_service_manager.erl
=> Add extensions.

src/partisan_hyparview_peer_service_manager.erl
When processing a join from a new node after adding it
to the active view, the contact node proceeds to forward
the join to it’s active view, the new joiner node should be
excluded.
=> Dont forward join to new node

src/partisan_default_peer_service_manager.erl
When sending to the local node through the API, ensure that we bypass the distribution library for performance and to avoid deadlocks.
=> On local send, bypass distribution.

src/partisan_default_peer_service_manager.erl
If partisan is being managed by an external membership service, then gossip can interfere with that based on races on updating the local membership with the remote membership.  Provide the ability to disable gossip if being managed externally.
=> Provide mechanism to disable gossip.

src/partisan_socket.erl
If a zero value is configured for the peer port variable
ensure that, after bind, the final system allocated port
number is obtained and set in the configuration.
=> Ensure peer port config var on system allocated port

Makefile, include/partisan.hrl, src/partisan_client_server_peer_service_manager.erl, src/partisan_config.erl, src/partisan_default_peer_service_manager.erl, src/partisan_hyparview_peer_service_manager.erl, src/partisan_peer_service.erl, src/partisan_peer_service_manager.erl, src/partisan_static_peer_service_manager.erl, test/partisan_SUITE.erl
=> Add synchronous join.

src/partisan_default_peer_service_manager.erl
=> update pending nodes in default manager update_members

src/partisan_default_peer_service_manager.erl, test/partisan_SUITE.erl
Adapt to use the new node specification format and only fire if it's the last connection to be closed for that node.
=> Fix broken on_down callback.

src/partisan_causality_backend.erl, src/partisan_config.erl, src/partisan_connection_cache.erl, src/partisan_default_peer_service_manager.erl, src/partisan_reliability_backend.erl, src/partisan_sup.erl, src/partisan_vclock.erl, src/vclock.erl, test/partisan_SUITE.erl
=> Causal ordering for default backend.

.travis.yml, include/partisan.hrl, src/partisan_rpc_backend.erl, src/partisan_sup.erl, src/partisan_util.erl, test/partisan_SUITE.erl
Add a mechanism to simulate the RPC behavior in Erlang using Partisan.
=> Add RPC mechanism.

.travis.yml, Makefile, bin/counterexample-find.sh, bin/counterexample-identify-support.escript, bin/counterexample-identify-support.sh, bin/counterexample-minimize-failures.escript, bin/demers-anti-entropy-test.sh, bin/demers-direct-mail-acked-test.sh, bin/demers-direct-mail-test.sh, bin/heaps.escript, bin/schedule-generator.escript, bin/wat-provenance.sh, include/partisan.hrl, protocols/bernstein_ctp.erl, protocols/demers_direct_mail_acked.erl, protocols/lampson_2pc.erl, protocols/skeen_3pc.erl, src/partisan_config.erl, src/partisan_pluggable_peer_service_manager.erl, src/partisan_trace_orchestrator.erl, src/partisan_util.erl, test/prop_partisan.erl, test/prop_partisan_crash_fault_model.erl, test/prop_partisan_reliable_broadcast.erl
Ensure that we generate schedules where faults are resolved, global assertions come at the end, and both commands and fault injections happen during execution but prior to fault resolution.
=> WIP: Add new scheduler prototype.

bin/check-hbbft.sh, src/partisan_hbbft_worker.erl, test/prop_partisan_hbbft.erl
reading the block adding code, this should sync the blocks, and running with BOOTSTRAP=true should handle the genesis block stuff.
=> WIP: add sync
